import Head from 'next/head'
export default function Test () {
    return <>
        <Head>
        <title>Portfolio Kosovo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css"></link>
      </Head>
        <p>Test, allá la están testeando</p>
    </>
}