export default function Characters(req, res) {
    // res.status(200).json(
        return(
        { razas: [
            {raza: "Humano", PV: 8, VM: 2, RD: 0, apt1: "Si tira un 1, cuenta como 2.", apt3: "el 1 y 2 cuentan como 3."},
            {raza: "Enano", PV: 10, VM: 0, RD: 1, apt1: "Gana RD +1.", apt3: "ignora venenos y cualquier efecto que reste VM."},
            {raza: "Elfo", PV: 6, VM: 3, RD: 0, apt1: "Gana 1d6 extra de acción.", apt3: "1xturno reroll de movimiento y elige."},
            {raza: "Orco", PV: 12, VM: 2, RD: 0, apt1: "+1 de daño en ataques con armas c/c, y +1 extra con 6 en el dado.", apt3: "+1 de daño con 5 en el dado y +2 con 6 (en lugar del +1)."},
            {raza: "Gnomo", PV: 6, VM: 1, RD: 0, apt1: "1/6 chance de evadir cualquier efecto (daño o no); +1 PE x piso.", apt3: "2/6 de chance, +1 PE x piso (total de +2)."},
            {raza: "Mediano", PV: 6, VM: 1, RD: 0, apt1: "1xturno reroll de cualquier d6; +1 en tiradas de encontrar cosas.", apt3: "cuando hace algún reroll, elige con cuál tirada quedarse; +1 en tiradas de abrir cosas."}
          ],
          clases: [
            {clase: "Guerrero", PV: 10, VM: 1, RD: 0, apt1: "Ataque en carga: 1xturno, si le sobró casillas de movimiento luego de moverse al menos dos casillas, lo transforma en un ataque que hace daño igual a la cantidad que le sobró (gastando ese movimiento restante); puede sumar el bono de arma y aptitudes, pero no puede activar efectos que dependan de efectuar un ataque.",
                "apt2+": [{requisitos: '', aptitud: "Armadura pesada: Obtiene VM +1. Además, puede usar la armadura más pesada (ver equipamientos)."},
                          {requisitos: '', aptitud: "Hendedura: Si derrota a una criatura con un ataque cuerpo a cuerpo, el daño excedente puede ser dirigido hacia otra criatura adyacente al guerrero. Éste se considera un ataque y añade bonos de daño (por arma, raza o aptitudes)."},
                          {requisitos: '', aptitud: "Maestría con arma cuerpo a cuerpo: Sus ataques cuerpo a cuerpo obtienen +1 al daño. Una vez por piso puede rerollear un dado de ataque y elegir, y sumar +1 extra de daño a ese ataque."},
                          {requisitos: 'Aptitud "Maestría con arma cuerpo a cuerpo"', aptitud: "Superioridad con arma cuerpo a cuerpo: El beneficio de reroll de una vez por piso de la maestría, se convierte en una vez por turno. El ataque en carga puede activar efectos que dependan de efectuar un ataque (como hendedura o ataque poderoso)."},
                          {requisitos: '', aptitud: "Ataque poderoso: Cuando efectúa un ataque y hace daño, puede inmediatamente gastar otro d6 de acción para hacer un nuevo ataque. Ambos ataques reciben todos los bonos correspondientes, pero se reduce su daño sólo una vez. El objetivo de estos ataques recibe un penalizador de -2 a su VM por un turno. El segundo ataque ignora cualquier efecto de errar o anular daño, ya que se suma al daño del primero."},
                          {requisitos: '', aptitud: "Puede hacer sus ataques a distancia de 6 casillas. No suma los bonos de ataques cuerpo a cuerpo. Una vez por piso, puede elegir un turno en el que sus ataques a distancia puedan rerollearse."} ],
                cdp: [{requisitos: '', aptitud: "Guerrero arcano: Elige un conjuro inicial de hechicero o mago (si tiene requisitos, debe cumplirlos). Puede lanzarlo una vez por turno. La armadura mágica no se suma con la armadura equipada. El siguiente ataque el mismo turno que usó el conjuro inicial, obtiene +1 al daño (si el conjuro inicial es un ataque, éste suma el +1)."},
                      {requisitos: '', aptitud: "Maestro en armas: Obtiene +1 al daño en todos sus ataques. 1xturno puede ignorar cualquier efecto de evasión o pifia, pero debe anunciarlo antes de realizar el ataque. Si tiene ataque a distancia, éste aumenta su rango en 2 casillas."}]
            },
            {clase: "Paladín", PV: 10, VM: 0, RD: 0, apt1: "Castigar: 1xturno suma +nivel al daño a un ataque que dio en el objetivo.",
                "apt2+": [{requisitos: '', aptitud: "Armadura pesada: Puede usar la armadura más pesada (ver equipamientos). Comprarla le cuesta 0 PP."},
                          {requisitos: '', aptitud: "Montura: Obtiene VM +3."},
                          {requisitos: '', aptitud: "Arma mágica: Al atacar con un arma comprada de equipamiento, obtiene +1 al daño y el castigar ignora RD."},
                          {requisitos: '', aptitud: "Imposición de manos: 1xturno puede usar 1d6 de acción para curarse a él, o una criatura adyacente. Puede eliminar un efecto negativo que le esté afectando al objetivo de la curación (veneno, pérdida de VM, pérdida de acción)."},
                          {requisitos: '', aptitud: "Bastión divino: Recibe 1 menos de daño de conjuros. Los objetivos del castigar reducen a la mitad las curaciones recibidas (redondeando hacia arriba) durante todo el piso (no se acumula, cuenta como estado negativo). 1xpiso, obtiene una acción extra."},
                          {requisitos: 'Aptitud "Montura"', aptitud: "Ataque montado: Si se movió hacia un enemigo (al menos una casilla), los ataques contra éste, durante este turno, obtienen +2 al daño y el primero puede ser rerolleado (moverse “hacia” un enemigo implica acortar la distancia en al menos una casilla)."} ],
                cdp: [{requisitos: '', aptitud: "Campeón divino: 1xpiso el objetivo del castigar, que haya recibido daño, pierde una acción en su siguiente turno (no se acumula con este mismo efecto). 1xpiso puede castigar una segunda vez en un mismo turno. 1xturno, en un turno que haya derrotado a una criatura mediante su castigar, puede usar su imposición de manos sin gastar acción (respetando el máximo por turno, y debe tener la aptitud para usarla)."},
                      {requisitos: 'Aptitud "Montura"', aptitud: "Cavalier: Obtiene la aptitud “Carga mortal”, que le da el siguiente beneficio. Gasta dos dados de acción y luego elige cuál será de movimiento y cuál de ataque; si tiene alguna aptitud que le permita rerollear un d6 de ataque o movimiento, puede hacerlo luego de haber elegido (rerolleando el dado correspondiente); luego, debe moverse un mínimo de dos casillas hacia su objetivo (si estaba más cerca, puede alejarse y acercarse) y realizar el ataque cuerpo a cuerpo; por último, cada 2 puntos de movimiento sobrantes, el ataque obtendrá 1 de daño, y pierde ese movimiento restante."}]
            },
            {clase: "Bárbaro", PV: 12, VM: 1, RD: 0, apt1: "1xturno puede rerollear un dado de daño y elegir.",
                "apt2+": [{requisitos: '', aptitud: "Furia: Durante su turno, si tiene 10+ de daño a sus PV, sus ataques hacen +2 de daño y obtiene +1VM."},
                          {requisitos: 'Aptitud "Furia"', aptitud: "Furia mayor: Durante su turno, si tiene 13+ de daño a sus PV, recibe 1d6 extra de acción."},
                          {requisitos: '', aptitud: "Curación rápida: Al inicio de su turno se cura 2 PV. 1xpiso al inicio de su turno remueve un efecto negativo que lo esté afectando."},
                          {requisitos: '', aptitud: "Frenesí: Una vez por piso, si queda en 0- PV, se levanta con 1 PV al inicio de su siguiente turno. Tendrá una acción menos en el turno que se levanta. Si este beneficio no se usó en un piso, obtiene +1 PE al final del mismo."},
                          {requisitos: '', aptitud: "Ataque en salto: 1xturno puede usar el bono extra de VM (sin tirar d6 de movimiento) para acercarse a una criatura y atacarla gastando normalmente una acción de ataque (siempre que quede adyacente a ésta y que disponga de la acción). Debe tener la acción disponible para poder usar esta aptitud, y debe invertirla en el ataque."},
                          {requisitos: '', aptitud: "Puede sacrificar 1 PV para volver a tener el beneficio del reroll de nivel 1. No puede rerollear dos veces el mismo ataque con esta aptitud."} ],
                cdp: [{requisitos: 'Aptitud "Frenesí"', aptitud: "Berserker frenético: Reemplaza la aptitud “frenesí” por la siguiente. Una vez por piso, si queda en 0- PV, no cae ni pierde más PV hasta el inicio de su siguiente turno; que lo empieza con nivel PV. Si este beneficio no se usó en un piso, obtiene +2 PE al final del mismo."},
                      {requisitos: '', aptitud: "Mágico de la furia: Elige un conjuro inicial de hechicero o mago (si tiene requisitos, debe cumplirlos), con excepción de armadura mágica. Puede lanzarlo una vez por turno. Puede sacrificar 2 PV para usar una segunda vez en el mismo turno."}]
            },
            {clase: "Mago", PV: 6, VM: 0, RD: 0, apt1: "Elige dos conjuros iniciales. No usa armadura equipada. Los conjuros pueden usarse sólo una vez por turno (cada uno)",
                "conjuros iniciales": [{requisitos: '', aptitud: "Armadura mágica: usa su dado de acción para ganar RD+2 durante todo el piso."},
                                       {requisitos: '', aptitud: "Proyectil mágico: Puede usar su acción de ataque para atacar a distancia (cualquiera) e ignorar RD. No suma bono de arma."},
                                       {requisitos: '', aptitud: "Ralentizar: Elige un área cuadrada de nivel casillas de lado; usa un d6 de acción para hacer que las criaturas dentro de esa área reduzcan en 3 su VM (no stackea consigo mismo), durante su siguiente turno. Una vez por piso, puede hacer que pierdan una acción las criaturas afectadas (además de la reducción de VM)."},
                                       {requisitos: '', aptitud: "Toque vampírico: Usa 1d6 de acción para hacer ese daño a una criatura adyacente, ignorando RD de armadura equipada, y curándose una cantidad igual al daño recibido por el objetivo."},
                                       {requisitos: 'sólo para enano', aptitud: "Tacle sobrecargado: Usa su dado de acción y se desplaza hasta 2 casillas; luego hace un ataque cuerpo a cuerpo normal que suma la RD del mago como daño extra. "},
                                       {requisitos: 'sólo para orco', aptitud: "Rayo vital: Realiza un ataque de 1d6 hasta a 6 casillas que suma su bono racial de daño; además puede sacrificar un PV para obtener +2 de daño."},
                                       {requisitos: 'sólo para elfo', aptitud: "Rayo dividido: Realiza un ataque de 1d6 que ignora hasta 1 de RD de armadura equipada. El ataque se divide en dos y puede impactar a dos objetivos diferentes hasta a 6 casillas de distancia (no pueden impactar a un mismo objetivo). Se consideran dos ataques, pero el daño de ambos es el mismo (el resultado del d6 + cualquier bono que corresponda)."}
                                    ],
                "apt2+": [{requisitos: '', aptitud: "Desplazamiento (conjuro): Usa un dado de acción y obtiene el siguiente beneficio para todo el piso: cada vez que es objetivo de un ataque, o estuviera por recibir un daño en área, tira 1d6; si saca 5 o 6, evade tales ataques. Este efecto se acumula con la aptitud del gnomo; en nivel 2 evade de 4 a 6, y desde nivel 3, evade de 3 a 6. Una vez evadidos NIVEL ataques, se va el conjuro."},
                          {requisitos: '', aptitud: "Presciencia menor (conjuro): Usa un dado de acción y obtiene el siguiente beneficio para todo el piso: Cualquier d6 puede considerar su resultado como 1 superior a lo obtenido, con excepción del 6. Una vez por piso puede anular un efecto o un daño que esté por afectar al mago (no hace falta que este conjuro esté en efecto)."},
                          {requisitos: '', aptitud: "Bola de fuego (conjuro): Usa un dado de acción para hacer 1d6 de daño en un área cuadrada de nivel casillas de lado, sin límite de distancia. No se reduce con RD de armadura equipada. Puede elegir qué criaturas no recibirán daño de esta bola de fuego."},
                          {requisitos: '', aptitud: "Maestría en conjuros ofensivos: Beneficio pasivo. Sus conjuros que hacen daño obtienen +1 al daño. Una vez por piso puede usar un mismo conjuro de daño dos veces en el mismo turno (si le alcanzan las acciones)."},
                          {requisitos: '', aptitud: "Maestría en conjuros defensivos: Beneficio pasivo. Una vez por turno, puede usar un conjuro defensivo (armadura mágica, desplazamiento) sin gastar acción. Mientras tenga algún conjuro defensivo activo, obtiene VM +2."},
                          {requisitos: '', aptitud: "Elige y aprende otro conjuro inicial. Cuando termina un piso con 10+ PV, recibe +3 PE."} ],
                cdp: [{requisitos: '', aptitud: "Mago especialista: Elige uno de sus conjuros iniciales disponibles; puede usarlo 2 veces por turno. Si el conjuro es armadura mágica, si lo usa mientras lo tenga en efecto, le da 3 de RD (en lugar de 2; no aumenta con lanzamientos posteriores y cuenta como un solo beneficio)."},
                      {requisitos: '', aptitud: "Mago de batalla: Los ataques cuerpo a cuerpo del mago de batalla contra criaturas que hayan recibido daño de un conjuro suyo este turno, ignoran RD de armadura. Los ataques cuerpo a cuerpo con arma equipada obtienen +1 al daño."}]
            },
            {clase: "Clérigo", PV: 8, VM: 0, RD: 0, apt1: "1xturno puede usar el d6 para curar 1d6 + nivel (a él u otro adyacente).",
                "apt2+": [{requisitos: '', aptitud: "Puede curar 2 veces xturno. 1xturno puede rerollear una curada (debe quedarse con el segundo resultado)."},
                          {requisitos: '', aptitud: "Arma de la deidad (conjuro): Si tiene un arma equipada, lanza 1d6 (gastando la acción) y obtiene para ese piso un bono al daño con esa arma; el bono es de +1 (con 1 o 2 en el d6), +2 (con 3 o 4) o +3 (con 5 o 6). Puede volver a usar este conjuro en otro turno, cambiando el bono según el nuevo resultado."},
                          {requisitos: '', aptitud: "Semblante de la deidad (conjuro): Usa un d6 de acción, dura todo el piso o hasta decidir destransformarse (en su turno, sin gastar dado de acción). Obtiene daño +1, sus conjuros de curación curan +1 y recupera 1 PV al inicio de cada turno."},
                          {requisitos: 'Conjuro "Semblante de la deidad"', aptitud: "Semblante mayor de la deidad (conjuro): Usa un d6 de acción y obtiene los beneficios de semblante de la deidad, y no se acumulan con éste. Además, obtiene extra RD +1 y puede 1xturno rerollear 1d6 (debe quedarse con el segundo resultado). Puede elegir iniciar con el conjuro activo desde el inicio del piso (antes de que empiece la primera ronda, sin gastar una acción), a cambio de perder el beneficio de reroll."},
                          {requisitos: '', aptitud: "Expulsar: Una vez por turno, afecta a todas las criaturas que no sean otros personajes (ni sus compañeros animales), dentro de nivel -1 casillas del clérigo. Lanza un d6 de acción y efectúa daño que no se reduce (ver tabla); además, una vez por piso, puede hacer que todas las criaturas dañadas pierdan una acción en su siguiente turno. Daño 2/3/4"},
                          {requisitos: '', aptitud: "Redirección de energía: Cuando cura al menos 1 PV, si el objetivo llenó todos sus PV y sobró curación, puede usar ese sobrante para curar o dañar a otro objetivo a nivel casillas del clérigo (elige uno, no ambos); si elige dañar, puede usar hasta un máximo de nivel puntos sobrantes. Aplica los bonos a curación/daño sobre ese sobrante. El daño no se reduce con armadura."} ],
                cdp: [{requisitos: 'Aptitud "Redirección de energía"', aptitud: ": 1xturno cuando usa su aptitud inicial no necesita elegir como objetivo a una criatura adyacente; lanza el dado y suma todos los bonificadores correspondientes; luego, elige a cualquier cantidad de objetivos a nivel casillas, y reparte la curación de cualquier manera entre los mismos."},
                      {requisitos: '', aptitud: ": Su aptitud inicial cura +1. 1xturno, cuando cura al menos 1 PV a cualquier criatura (incluido sí mismo), puede eliminarle un efecto negativo (se elimina luego de efectuada la curación, no requiere acción). 1xpiso, como acción, elimina un efecto negativo de TODA criatura hasta a nivel casillas."}]
            },
            {clase: "Druida", PV: 8, VM: 0, RD: 0, apt1: "Forma salvaje: Usa un d6 de acción, dura todo el piso o hasta decidir destransformarse (en su turno, sin gastar dado de acción) RD +1 daño +1 a ataques cuerpo a cuerpo, no puede usar conjuros, no cuenta el bono de arma para el daño. Elige un conjuro inicial.",
            "conjuros iniciales": [{requisitos: '', aptitud: "Curar: 1xturno usa su d6 para curarse a sí mismo o a un adyacente."},
                                   {requisitos: '', aptitud: "Enmarañar: Usa su d6 para reducir en 2 la VM de criaturas un turno en un área de 1d6 de lado, empezando ésta a nivel casillas de distancia."},
                                    ],
                "apt2+": [{requisitos: '', aptitud: "Compañero animal: Obtiene una criatura aliada que actúa en el mismo turno que el druida y se coloca en alguna casilla adyacente al mismo, al inicio del piso. Tiene las siguientes estadísticas: PV = nivel x2, se mueve hasta 3 casillas por turno (sin gastar d6 de acción), tiene 1d6 de acción para ataque o movimiento. Reaparece con sus PV llenos al inicio de cada piso."},
                          {requisitos: '', aptitud: "Forma salvaje mayor: Su forma salvaje obtiene beneficios extra; cuando se transforma gana VM +1, daño +1 a ataques cuerpo a cuerpo y puede usar conjuros iniciales. A partir de nivel 3 de pj, puede usar cualquier conjuro."},
                          {requisitos: '', aptitud: "Espinas (conjuro): Usa su d6 de acción para obtener un beneficio durante todo el piso; cada vez que ataca cuerpo a cuerpo a una criatura adyacente, ésta recibe 1 de daño que no se reduce; cada vez que es atacado cuerpo a cuerpo por una criatura adyacente, ésta recibe 2 de daño que no se reduce."},
                          {requisitos: 'Aptitud "Compañero animal"', aptitud: "Vínculo animal: Pasivo. Cuando el druida usa un conjuro en sí mismo, el compañero animal recibe el mismo efecto. 1xturno, antes de que actúe su compañero animal, éste puede teletransportarse a una casilla adyacente al druida (sólo si hay alguna disponible); este efecto reemplaza al movimiento gratis de ese turno. Por último, el compañero animal tiene nivelX3 PV (en lugar de nivelX2)."},
                          {requisitos: '', aptitud: "Regeneración (conjuro): Usa su d6 y obtiene un beneficio durante todo el piso. Al final de cada turno (suyo), se cura 2 (con 1, 2 o 3 en un d6) o 3 (con 4, 5 o 6) PV."},
                          {requisitos: '', aptitud: "Llamar rayo (conjuro): Usa su d6 y obtiene un beneficio durante todo el piso. En cada turno, puede usar hasta un dado de acción para hacer daño a una criatura en cualquier ubicación, que no se reduce con armadura y recibe un bono al daño = número de ronda -1. En nivel 3 puede dañar a 2 criaturas adyacentes (con la misma tirada). En nivel 5 puede dañar a una tercera, adyacente a alguna de las otras."} ],
                cdp: [{requisitos: 'Conjuro inicial "Curar"', aptitud: "Hierofante: Su conjuro curar cura +2 y puede elegir como objetivo a una criatura a cualquier distancia en el piso. Opcionalmente, puede usar curar sin gastar acción, pero perdiendo los beneficios anteriores (decide cada vez que lo quiera usar)."},
                      {requisitos: 'Aptitud "Forma salvaje mayor"', aptitud: "Combatiente de la naturaleza: Cuando usa forma salvaje, obtiene RD +1 adicional. 1xpiso puede obtener un penalizador de VM -3 durante 1 turno, para usar su forma salvaje sin gastar acción, durante ese turno."}]
            },
            {clase: "Explorador", PV: 8, VM: 1, RD: 0, apt1: "Elige uno: 1- Combate con dos armas: 1xturno, cuando usa 1d6 de acción para atacar, lanza otro d6 extra de ataque. El explorador puede comprar una segunda arma para obtener daño por arma para su ataque extra (el arma extra sólo sumará daño a ataques extra de combate con dos armas). 2- Arquería: Sus ataques pueden ser de rango 6 casillas.",
                "apt2+": [{requisitos: 'Nivel 3 o más y aptitud inicial "Combate con dos armas"', aptitud: "Combate con dos armas mejorado: Elimina la restricción de 1xturno del combate con dos armas."},
                          {requisitos: 'Nivel 3 o más y aptitud inicial "Arquería"', aptitud: "Disparo a bocajarro: Sus ataques de rango reciben daño extra según la distancia a la que se encuentre su objetivo: (Casillas de distancia/Daño) 1/0, 2/4, 3/3, 4/2, 5/1, 6/0"},
                          {requisitos: '', aptitud: "Presa/enemigo predilecto: 1xturno, usa su dado de acción para elegir una criatura y obtener dos beneficios contra ella durante todo el piso o hasta que vuelva a usar esta aptitud. 1- Obtiene +1 de daño contra ella; 2- 1xturno, en un turno en el que le haya hecho daño, puede moverse hasta su bono de VM sin gastar acción."},
                          {requisitos: '', aptitud: "Puede elegir la aptitud inicial que no eligió en nivel 1. Las armas le cuestan 1 PP menos."},
                          {requisitos: '', aptitud: "Aptitud animal (conjuro): Usa un dado de acción para elegir un beneficio que dura todo un piso: 1- RD +1. 2- VM +1 y +1 al daño en un ataque por turno. Si posee compañero animal, éste recibirá el mismo beneficio."},
                          {requisitos: '', aptitud: "Compañero animal: Obtiene una criatura aliada que actúa en el mismo turno que el explorador y se coloca en alguna casilla adyacente al mismo, al inicio del piso. Tiene las siguientes estadísticas: PV = nivel x2, se mueve hasta 3 casillas por turno (sin gastar d6 de acción), tiene 1d6 de acción para ataque o movimiento. Reaparece con sus PV llenos al inicio de cada piso."} ],
                cdp: [{requisitos: 'Aptitud "Presa/Enemigo predilecto"', aptitud: "Cazador: 1xturno, usando un d6 de acción, puede tirar una trampa a un casillero hasta a nivel casillas de distancia. La trampa dura todo el piso. Puede tener hasta nivel trampas al mismo tiempo; si lanza una que excedería este límite, remueve otra a elección. Cualquier criatura (aliada o enemiga) que pise una trampa resta 3 casillas a su movimiento total durante ese turno, y recibe 2/3/4 de daño que no se reduce con RD de armadura equipada; si se lanza una trampa a una casilla ocupada, afectará a la criatura al inicio de su turno; si la criatura está -además- afectada por “presa/enemigo predilecto”, pierde una acción. Cuando una trampa se activa, se remueve del piso."},
                      {requisitos: 'Aptitud inicial "Arquería"', aptitud: "Arquero arcano: Sus ataques a distancia obtienen +2 casillas de distancia. 1xturno, un ataque a distancia obtiene +2 al daño e ignora RD de armadura."}]
            },
            {clase: "Pícaro", PV: 8, VM: 1, RD: 0, apt1: "Puede rerollear cualquier tirada de encontrar o abrir cosas, 1xtirada. Ataque de rango 2 casillas en nivel 1, 3 casillas en nivel 2-3, 4 casillas en nivel 4-5.",
                "apt2+": [{requisitos: '', aptitud: "Acción astuta: Obtiene VM +1. Durante su turno puede moverse hasta su bono de VM sin gastar acción (ni tirar el d6). Especial: el elfo no obtiene el beneficio pasivo de VM +1, pero puede moverse gratis VM +2 (en lugar de sólo VM)."},
                          {requisitos: '', aptitud: "Uso de veneno: Sus ataques que causen daño aplican veneno (1 turno), que tiene las siguientes características sobre el afectado (si no evita el efecto de veneno): disminuye en 1 la VM, acumulativamente, y en el inicio del turno le hace 1, 2 o 3 de daño que no se reduce con RD de armadura (tira 1d6 para calcular el daño), mínimo 1, también acumulativo (pero cuentan como daños diferentes)."},
                          {requisitos: '', aptitud: "Obtiene VM +1, puede encontrar tesoros más de una vez por turno y recibe +1 PP si abre una cerradura de paso de piso. Por último, puede obtener +1 en su primera tirada de encontrar tesoros de un turno, pero no podrá buscar una segunda vez en ese mismo turno."},
                          {requisitos: 'Aptitud "Acción astuta"', aptitud: "Rodar a la defensiva: 1 vez por ronda puede restar hasta su bono de VM de una fuente de daño, pero gasta la acción astuta de su siguiente turno."},
                          {requisitos: '', aptitud: "Finta y ataque furtivo: (debe tener un arma equipada, apropiada al tipo de ataque -c/c o distancia-). 1xturno puede tirar 1d6 de movimiento (sumando todos los bonos correspondientes) y usar el resultado como un ataque (no suma bonos de ataque pero aplica veneno, si lo tiene)."},
                          {requisitos: '', aptitud: "Sigilo: Si pasa todo un turno sin atacar y se movió al menos una casilla, terminando adyacente a un obstáculo y a ninguna otra criatura, puede esconderse (no requiere acción). Al estar escondido, no es objetivo de ataques de criaturas; además, un jugador (actuando como enemigo) que quiera encontrarlo, debe hacer una tirada de encontrar tesoro y superar una cantidad = nivel de pícaro + bono de pícaro a encontrar tesoros; si lo encuentra, lo revela ante todas las criaturas del piso. El efecto dura hasta el inicio de su siguiente turno."} ],
                cdp: [{requisitos: 'Aptitud "Finta y ataque furtivo"', aptitud: "Bribón arcano: elige un conjuro inicial que haga daño, de hechicero o mago (si tiene algún requisito, debe cumplirlo); puede usarlo una vez por turno. Puede usar finta y ataque furtivo con este conjuro inicial; es decir, en lugar de usar el d6 para el daño del conjuro, usa el daño del ataque furtivo."},
                      {requisitos: 'Aptitud "Sigilo"', aptitud: "Asesino: Elimina la restricción de terminar adyacente a un obstáculo, en la aptitud de sigilo. Además, el primer ataque en el siguiente turno que usó sigilo sumará nivel al daño. 1xpiso puede activar su sigilo de la siguiente manera (obviando los requisitos y la mecánica del uso normal): usa 1d6 de acción y entra en sigilo; al usar sigilo de esta manera, si ataca en el mismo turno -luego de usar sigilo-, sumará nivel al daño (en lugar del primer ataque del siguiente turno). Gana 1 PP adicional si derrotó al menos a un enemigo con un ataque que sume el daño extra por sigilo."}]
            },
            {clase: "Monje", PV: 8, VM: 2, RD: 0, apt1: "Desviar proyectiles. Una vez por ronda, cuando recibe un proyectil (ataque a distancia) no mágico, puede tirar 1d6 (gratis); reduce la cantidad resultante + nivel -1, del daño que recibiría del proyectil (este efecto no cuenta como RD). No usa armadura equipada.",
                "apt2+": [{requisitos: '', aptitud: "Ataque aturdidor: Chance de hacer perder 1d6 de acción, cuando ataca y hace daño; no gasta acción pero puede intentarse sólo una vez por turno (elige cuándo). Para que se active el efecto, debe obtener 4, 5 o 6 en un d6 (se tira aparte del ataque). La criatura afectada recibirá 1 de daño extra de este ataque (no cuenta como bono de daño), si es que recibe el efecto de perder acción."},
                          {requisitos: '', aptitud: "Desviar mejorado: Desviar ahora reduce 1d6 + nivel (en lugar de 1d6 + nivel -1). Puede usar su aptitud de desviar proyectiles con proyectiles mágicos y ataques cuerpo a cuerpo; sin embargo, si lo usa para lo último, no obtiene el nivel a la reducción de daño (este efecto no cuenta como RD)."},
                          {requisitos: '', aptitud: "Uso de Ki: Obtiene 1d6 de acción extra, que sólo puede usarse para una de dos opciones: 1- curarse a sí mismo, 2- hacer un ataque que no suma bonos de daño."},
                          {requisitos: '', aptitud: "Obtiene +2 de daño contra criaturas a las que les hizo perder una acción en su turno anterior o en éste. 1xpiso, usa un d6 de acción para atacar a las criaturas enemigas adyacentes, con el siguiente efecto: hace 1 de daño que no se reduce, y les hace perder una acción en su siguiente turno (a las criaturas que recibieron el daño); este efecto no se apila con la pérdida de acción del ataque aturdidor."},
                          {requisitos: 'Aptitud "Uso de ki"', aptitud: "Uso mejorado de Ki: Con uso de Ki, la curación obtiene +1 y puede curar a un aliado adyacente; y el ataque extra puede elegir una de las siguientes modificaciones: 1- sumar bonos de daño, 2- ser a distancia de nivel casillas."},
                          {requisitos: 'Aptitud "Ataque aturdidor"', aptitud: "Ataque aturdidor mejorado: Hace perder acción con 3, 4, 5, 6. Puede intentar dos veces por turno, pero no hace perder más de una acción a la misma criatura en el mismo turno."} ],
                cdp: [{requisitos: '', aptitud: "Maestro borracho: Cuando compra pociones, compra 2 por 1 PP (en lugar de una). No tiene límite a la cantidad de pociones que puede cargar. En un turno que consumió una poción, sus ataques obtienen +1 al daño y su desviar obtiene +1 hasta el inicio de su siguiente turno. 1xpiso, puede consumir una poción sin gastar acción."},
                      {requisitos: 'Aptitud "Uso de ki"', aptitud: "Puño iluminado: elige un conjuro inicial de hechicero o mago (si tiene algún requisito, debe cumplirlo); puede usarlo una vez por turno. Los ataques sin arma equipada obtienen +1 al daño."}]
            },
            {clase: "Bardo", PV: 6, VM: 1, RD: 0, apt1: "1xturno usa su dado de acción para que él y otras criaturas que elija dentro de 1d6 +nivel casillas, obtengan +1 a cualquier d6 (sólo uno por criatura) hasta el inicio del siguiente turno del bardo; si el d6 es para una tirada en una tabla con 6 opciones, el máximo será 6. Puede utilizar otro dado de acción para reforzar su música, extendiendo el bono a cualquier cantidad de d6 que use cada criatura y curándolos 1 PV.",
                "apt2+": [{requisitos: '', aptitud: "Hombre de mundo: Obtiene 2 PP adicional en cada piso. Obtiene unas botas y hasta una poción; si ya posee botas, obtiene hasta una poción extra. No puede exceder el límite de pociones con esta aptitud."},
                          {requisitos: 'Aptitud "Hombre de mundo"', aptitud: "Carismático: Obtiene 2 PP adicional en cada piso (que se acumula con hombre de mundo). Obtiene una armadura; si ya tiene una, obtiene hasta dos pociones, siempre que no exceda el límite."},
                          {requisitos: '', aptitud: "Virtuoso: Puede activar ambos efectos de su aptitud inicial con una sola acción. La curación mejora en +1."},
                          {requisitos: '', aptitud: "Sonata discordante: 1xturno, en un turno en el que usó su aptitud inicial, puede usar un d6 de acción para hacer 2 de daño hasta a nivel criaturas, dentro de un área cuadrada de 1d6 de lado (en cualquier ubicación del piso). Elige qué criaturas dentro del área no recibirán daño. Este daño no se reduce. Una vez por piso, puede elegir que su sonata discordante haga perder una acción a las criaturas afectadas."},
                          {requisitos: '', aptitud: "Melodía sugestiva: 1xpiso, en un turno en el que usó su aptitud inicial, puede usar un d6 de acción y elegir dos objetivos. Estos se considerarán enemigos entre ellos durante una ronda y se atacarán (o intentarán) en sus correspondientes turnos. Si alguno de los objetivos recibe daño que no sea causado por ellos antes de pasada la ronda, dejará de considerar enemigo al otro (por esta aptitud) y actuará normalmente. Una vez usada esta aptitud, obtiene el siguiente beneficio por este piso: 1xpiso puede hacer rerollear un d6 a una criatura enemiga."},
                          {requisitos: '', aptitud: "Conjuro prismático (conjuro, mínimo nivel 3): 1xturno, usa 1d6 de acción y obtiene algún efecto según la siguiente tabla:"
        //  "                 Dado   -                                     Efecto
        //   1          Elige una criatura y recibe 1 de daño que no se reduce
        //   2          Elige una criatura y recibe 1d6 de daño que no se reduce
        //   3          Elige una criatura y recibe 1d6 de daño que no se reduce y disminuye su VM en 2.
        //   4          Elige nivel criaturas hasta a nivel +1 casillas de distancia, reciben 1d6 que no se reduce.
        //   5          Igual que el 4; además disminuye su VM en 3 por un turno.
        //   6          Igual que el 4; además disminuye su VM en 3 y su daño en 1, por un turno." 
                          } ],
                cdp: [{requisitos: 'Nivel 3 o mayor', aptitud: "Acorde sublime: Obtiene 1 PP adicional en cada piso (que se acumula con otras aptitudes). 1xpiso puede usar canto de eternidad: elige cualquier criatura en el piso y, hasta el inicio del siguiente turno del acorde sublime, el objetivo deja de considerarse criatura y se considera obstáculo; no puede ser afectado de ninguna manera (ni daño, ni efectos; efectivamente, como un obstáculo) y salta su turno; este efecto no puede eliminarse antes de tiempo, ni puede ser evadido. Si el objetivo es un aliado, debe ser voluntario."},
                      {requisitos: '', aptitud: "Cantor de guerra: Cuando activa ambos efectos de su aptitud inicial, todas las criaturas afectadas reciben +1 de daño adicional a sus ataques con armas equipadas. 1xpiso, puede hacer que el +1 sea a cualquier tipo de ataque, y que la curación mejore en +1."}]
            },
            {clase: "Caballero", PV: 10, VM: 0, RD: 0, apt1: "Reto: 1xturno tira 1d6 de acción, designa a un objetivo y obtiene +2 o +3 de daño (+2 con 1, 2 o 3 en el dado; +3 con 4, 5 o 6) y RD +1 contra éste durante todo un piso. Si se vuelve a usar la aptitud, reasigna los beneficios contra el nuevo objetivo, pero sólo si el anterior quedó fuera de combate.",
                "apt2+": [{requisitos: '', aptitud: "Montura: Obtiene VM +2 y daño +1."},
                          {requisitos: 'Aptitud "Montura"', aptitud: "Combate montado: Ignora los efectos que reducen VM. Puede rerollear sus ataques."},
                          {requisitos: '', aptitud: "Armadura completa: Puede usar la armadura pesada. Recibe -1 de daño de armas a distancia equipadas."},
                          {requisitos: '', aptitud: "Reto mejorado: Cuando derrota a una criatura a la que seleccionó con su reto, gana 1 PP adicional; además puede seleccionar otro objetivo sin gastar acción, al final del turno. Los PP ganados de esta manera no pueden invertirse en PE. Los PP sobrantes se pierden."},
                          {requisitos: '', aptitud: "Reto inmortal: Una vez por piso, si queda en 0- PV como resultado del daño provocado por una criatura designada por el reto, se levanta con nivel PV al inicio de su siguiente turno. Si este beneficio no se usó en un piso, obtiene +1 PE al finalizar."},
                          {requisitos: 'Aptitud "Combate montado"', aptitud: "Combate montado mejorado: Cuando rerollea los ataques de combate montado, puede elegir con cuál quedarse. 1xturno puede moverse hasta su VM sin gastar acción."} ],
                cdp: [{requisitos: 'Aptitud "Montura"', aptitud: "Cavalier: Obtiene la aptitud “Carga mortal”, que le da el siguiente beneficio. Gasta dos dados de acción y luego elige qué serán esas acciones, entre movimiento y ataque (puede elegir dos acciones de ataque, si posee combate montado mejorado, y moverse con esa aptitud lo requerido); si tiene alguna aptitud que le permita rerollear un d6 de ataque o movimiento, puede hacerlo luego de haber elegido (rerolleando el dado correspondiente); luego, debe moverse un mínimo de dos casillas hacia su objetivo (si estaba más cerca, puede alejarse y acercarse) y realizar el ataque cuerpo a cuerpo; luego, cada 3 puntos de movimiento sobrantes, el ataque obtendrá 1 de daño, y pierde el movimiento restante. Si eligió dos acciones de ataque, suma el daño total y cuenta como un solo ataque."},
                      {requisitos: '', aptitud: "Duelista: Uno versus uno: Cuando se encuentre adyacente a una criatura enemiga, si cada uno es la única criatura adyacente del otro, el duelista obtiene +2 al daño contra ella. 1xpiso, si el enemigo es además el objetivo del reto, obtiene +1 de daño extra contra ella durante 1 turno."}]
            },
            {clase: "Alquimista", PV: 8, VM: 0, RD: 0, apt1: "Bombas: Puede hacer ataques a distancia de 4 casillas, que no se reduce con RD de armadura equipada. No suma bono por arma a distancia. Elige 3 casillas adyacentes a la del objetivo, que formen un cuadrado con la misma; las criaturas en esas casillas, a elección del alquimista, reciben 1 de daño que no se reduce con RD de armadura.",
                "apt2+": [{requisitos: '', aptitud: "Bombas potentes: +2 casillas de rango del ataque de las bombas. +1 al daño de las bombas, tanto al objetivo principal como a las adyacentes elegidas en el ataque."},
                          {requisitos: '', aptitud: "Pociones: 1xturno puede gastar un d6 de acción para crear y usar una poción con un efecto, de los dos descriptos a continuación: 1- Poción de curación; se cura 3 (con 1 o 2 en el dado), 4 (con 3 o 4) o 5 (con 5 o 6) de PV. 2- Mutágeno; Obtiene para todo el piso RD +1 y VM +1 (no se acumula consigo mismo)."},
                          {requisitos: '', aptitud: "Alquimia potenciada: Las pociones creadas y las compradas, lo curan +1. El mutágeno le otorga VM +1 adicional. Las bombas pueden sumar el bono de arma a distancia. 1xpiso, si posee la aptitud pociones, puede crear y usar una poción con las siguientes características: elimina todo efecto negativo del alquimista y obtiene 1 PP adicional al final del piso."},
                          {requisitos: '', aptitud: "Bombas explosivas: Cuando ataca con bombas, en lugar de elegir 3 casillas adyacentes, elige todas las adyacentes que quiera. +1 al daño de bombas al objetivo principal y adyacentes."},
                          {requisitos: 'Nivel 3 o mayor', aptitud: "Bombas rápidas: Si usó al menos dos acciones de ataque con bombas a un objetivo en el mismo turno, puede hacer un ataque extra con bomba al mismo objetivo (sin gastar acción). Opcionalmente, si el objetivo cayó con el ataque previo al extra de esta aptitud, puede atacar su casilla para hacer daño a los adyacentes correspondientes."},
                          {requisitos: 'Aptitud "Pociones"', aptitud: "Mutágeno mejorado: Estando activo el mutágeno, otorga VM +1, +1 al daño de ataques y se cura 1 PV al final de cada turno (del alquimista)."} ],
                cdp: [{requisitos: 'Aptitud "Pociones"', aptitud: "Mercader: Las pociones de curación creadas con la aptitud pociones, son iguales a las de equipamiento (curan 5/6/7) y puede usarla en un aliado adyacente. 1xpiso, puede crear una poción de restablecimiento (como la de equipamiento) y usarla en sí mismo o en un aliado adyacente. Si posee alquimia mejorada, la poción que le da 1 PP, da -en su lugar- 2 PP."},
                      {requisitos: 'Aptitud "Bombas explosivas"', aptitud: "Bombardero: Los ataques de bomba ya no son contra un objetivo, si no en un área cuadrada de 3 casillas de lado. Todas las casillas reciben el daño principal y no hay daño a adyacentes (considera la casilla del medio del cuadrado, para calcular el rango del ataque). El daño no se reduce con RD de armadura. Si posee la aptitud bombas rápidas, la mecánica cambia de la siguiente manera: el requisito ya no es el de atacar dos veces a la misma criatura, sino atacar dos veces la misma área; el beneficio es un tercer ataque a la misma área."}]
            },
            {clase: "Hechicero", PV: 6, VM: 0, RD: 0, apt1: "Elige un conjuro inicial. Cada conjuro inicial puede ser usado máximo dos veces por turno (con sus respectivas acciones). Los demás conjuros pueden ser usados máximo una vez por turno (cada uno). No puede usar armadura equipada.",
                "conjuros iniciales": [{requisitos: '', aptitud: "Armadura mágica: usa su dado de acción para ganar RD+2 durante todo el piso."},
                {requisitos: '', aptitud: "Saeta de fuego: Puede usar su acción de ataque para atacar a distancia de 6 casillas e ignora RD de armadura equipada. No suma bono de arma. Una criatura enemiga adyacente al objetivo recibe 1 de daño (se aplican daños extras, como el de magia caótica) que no se reduce con RD de armadura."},                
                {requisitos: '', aptitud: "Toque vampírico: Usa 1d6 de acción para hacer ese daño a una criatura adyacente, ignorando RD de armadura equipada, y curándose una cantidad igual al daño recibido por el objetivo."},
                {requisitos: 'sólo para enano', aptitud: "Tacle sobrecargado: Usa su dado de acción y se desplaza hasta 2 casillas; luego hace un ataque cuerpo a cuerpo normal que suma la RD del mago como daño extra. "},
                {requisitos: 'sólo para orco', aptitud: "Rayo vital: Realiza un ataque de 1d6 hasta a 6 casillas que suma su bono racial de daño; además puede sacrificar un PV para obtener +2 de daño."},
                {requisitos: 'sólo para elfo', aptitud: "Rayo dividido: Realiza un ataque de 1d6 que ignora hasta 1 de RD de armadura equipada. El ataque se divide en dos y puede impactar a dos objetivos diferentes hasta a 6 casillas de distancia (no pueden impactar a un mismo objetivo). Se consideran dos ataques, pero el daño de ambos es el mismo (el resultado del d6 + cualquier bono que corresponda)."}
                                       ],
                "apt2+": [{requisitos: '', aptitud: "Herencia dragonil: Si usa al menos un conjuro de fuego (saeta de fuego, bola de fuego), obtiene el siguiente beneficio hasta el inicio de su próximo turno: Los enemigos adyacentes reciben, al inicio de su turno, 1 de daño por cada conjuro de fuego usado (acumulativo, cuenta como una sola fuente de daño), que no se reduce."},
                          {requisitos: '', aptitud: "Magia caótica: 1xturno, cuando usa su primer conjuro que hace daño, tira 1d6 (sin gastar acción). Obtiene un efecto adicional según la siguiente tabla:"
                        // "  Dado   -   Efecto
                        //       1      -  El hechicero puede desplazarse hasta dos casillas (a elección)
                        //       2      -  Se cura 1 PV
                        //       3      -  Hace +2 de daño
                        //       4      -  Puede rerollear el daño y elegir. Hace +1 de daño
                        //       5      -  Puede rerollear el daño y elegir. Hace +1 al daño. Se cura 1 PV.
                        //       6      -  Durante todo el piso, sus siguientes conjuros hacen +1 de daño (no acumulativo con este efecto). Hace                +2 de daño, puede desplazarse hasta dos casillas."
                            },
                          {requisitos: '', aptitud: "Teletransportar (conjuro): Usa su acción para teletransportarse a cualquier casilla del piso; puede teletransportar al mismo tiempo a otros objetivos, pero el hechicero elige las casillas de destino. Los objetivos deben encontrarse a máximo nivel casillas del hechicero; si se trata de un pj, debe ser voluntario."},
                          {requisitos: '', aptitud: "Celeridad (conjuro): Usa un d6 de acción para obtener dos d6 de acciones que pueden ser usadas sólo en conjuros iniciales. Obtiene VM -2 hasta el inicio de su próximo turno. Este conjuro sólo puede usarse si es la primera acción que gaste en su turno."},
                          {requisitos: '', aptitud: "Bola de fuego (conjuro): Usa un dado de acción para hacer 1d6 de daño en un área cuadrada de nivel casillas de lado, sin límite de distancia. No se reduce con RD de armadura equipada. Puede elegir qué criaturas no recibirán daño de esta bola de fuego."},
                          {requisitos: '', aptitud: "Invocar conjuro inicial (conjuro). Usa un dado de acción y elige cualquier conjuro inicial al cual pudiera haber accedido en nivel 1; obtiene los efectos de ese conjuro (como si lo hubiera lanzado con la activación de este conjuro). No cuenta como el lanzamiento de un conjuro inicial (no afecta al límite de usos por turno de un mismo conjuro inicial)."} ],
                cdp: [{requisitos: 'Aptitud "Herencia dragonil"', aptitud: "Discípulo del dragón: 1xturno puede usar una vez adicional un conjuro de fuego (con su correspondiente acción; sólo aumenta el límite de usos por turno). 1xpiso sus conjuros de fuego hacen +1 al daño durante un turno."},
                      {requisitos: '', aptitud: "Tejedor del destino: Rerollea cualquier 1 tirado en un d6. 1xpiso suma +2 a cualquier tirada de d6 menor que 5 (previo a sumar cualquier bonificador; es decir, menor que 5 sólo en el dado)."}]
            },
            {clase: "Oráculo", PV: 6, VM: 0, RD: 0, apt1: "Reserva de adivinación: Obtiene una reserva de puntos de adivinación = nivel. La reserva de puntos se llena al inicio de cada ronda. El oráculo puede gastar un punto de su reserva para lanzar un dado al inicio de su turno; luego, durante su turno, DEBE usar el resultado en alguna de sus acciones (sin lanzar el dado en la acción, reemplazándola por el resultado previo). Puede guardar tantos resultados como acciones tenga, siempre que le alcancen los puntos de la reserva. Al final de su turno, él o una criatura a nivel casillas, pueden curarse PV = puntos disponibles de la reserva. No puede usar armadura equipada.",
                "apt2+": [{requisitos: '', aptitud: "Reserva superior: La reserva de puntos de adivinación aumenta en 1 (en total tendrá nivel +1). La curación por puntos no gastados es igual a 2Xpunto."},
                          {requisitos: '', aptitud: "Revelación: La cantidad de resultados que puede guardar ya no se limita por las acciones que tenga. Sin embargo, todas las acciones que efectúe durante su turno, deben gastar un resultado guardado (mientras lo haya, aunque la acción no requiera tirar un d6). Los resultados guardados que sobren, quedan guardados hasta justo antes del inicio de su siguiente turno. Una vez por ronda, puede intercambiar un resultado guardado SOBRANTE, por el resultado de un d6 de cualquier otra criatura."},
                          {requisitos: '', aptitud: "Precognición: Una vez por ronda, puede reducir el daño recibido de una fuente en una cantidad = reserva de puntos de adivinación. En su siguiente turno, la reserva recargará un punto menos (tendrá un punto menos disponible). Una vez por piso, puede rerollear cualquier cantidad de resultados guardados."},
                          {requisitos: '', aptitud: "Curar (conjuro): 1xturno, usa un dado de acción para curar a sí mismo o a una criatura adyacente, 1d6 + puntos totales de la reserva."},
                          {requisitos: 'Nivel 3 o mayor', aptitud: "Misterios: Puede gastar 2 puntos de su reserva para que un ataque sea sin límite de distancia; se convierte en “mágico” y “a distancia”; no suma bono de daño por armas equipadas e ignora cualquier reducción. Si posee el conjuro “curar”, puede gastar 1 punto de su reserva para que, al usarlo, seleccione a cualquier criatura del piso (sin importar la distancia). 1xpiso puede usar un dado de acción para eliminar efectos negativos en criaturas a nivel casillas de distancia (incluido él mismo); para eliminar un efecto, debe gastar un punto de su reserva (eliminar 1 efecto en una criatura y 2 efectos en otra, le costaría 3 puntos de su reserva)."},
                          {requisitos: 'Aptitud "Revelación"', aptitud: "Revelación final (requiere Revelación): 1xpiso, él o un aliado al que pueda ver, se levanta al inicio de su siguiente turno, luego de haber caído en combate (el oráculo elige). La criatura afectada, se reincorpora con una cantidad de PV igual a 3xresultados guardados (al momento de caer), mínimo 1 PV, sin superar los PV máximos. Si este beneficio se usó al menos una vez en un piso, obtiene +1 PE al final del mismo."} ],
                cdp: [{requisitos: 'Aptitud "Precognición"', aptitud: "Vidente: puede usar precognición para reducir el daño recibido por cualquier aliado en el piso, no sólo él. Considera al sobrante de puntos de adivinación como +1 para calcular cuánto cura su aptitud inicial al final del turno."},
                      {requisitos: 'Aptitud "Revelación"', aptitud: "Guía espiritual: 1xronda puede rerollear cualquier d6 de cualquier criatura; luego, elige una de tres opciones: 1- elegir con cuál tirada quedarse, 2-sumar 1 al resultado, o 3- restar 1 al resultado. El guía espiritual elige el reroll inmediatamente después de la tirada original, previo a un reroll que pudiera tener la criatura."}]
            },
            {clase: "Ninja", PV: 8, VM: 1, RD: 0, apt1: "No puede usar armadura equipada. Forma fantasmal: 1xturno, cuando usa una acción de movimiento, todo el movimiento que provenga de esa acción, permite traspasar cualquier casilla (ocupada por criaturas u obstáculos), siempre que no finalice en una casilla ocupada. Si efectúa una acción ofensiva mientras tiene este beneficio, lo pierde por el resto del turno: tal ataque ignora hasta 2 de RD.",
                "apt2+": [{requisitos: '', aptitud: "Forma fantasmal mejorada: El beneficio de forma fantasmal dura todo el turno cuando se activa, y no se va con una acción de ataque. Ignora hasta nivel de RD (en lugar de 2)."},
                          {requisitos: '', aptitud: "Armamento ninja: Obtiene un ataque de distancia de 4 casillas, si tiene un arma a distancia equipada. Los ataques con armas equipadas obtienen +1 al daño."},
                          {requisitos: '', aptitud: "Uso de ki: 1xturno, obtiene una acción adicional que puede usarse sólo en una de las siguientes opciones: 1- obtiene +1 de RD hasta el inicio de su siguiente turno; 2- estando en forma fantasmal, usa esta acción y se vuelve invisible hasta el inicio de su siguiente turno, lo que ocasiona que los enemigos no puedan fijarlo como objetivo; este beneficio se va si efectúa un ataque (aunque posea forma fantasmal mejorada)."},
                          {requisitos: 'Aptitud "Uso de ki"', aptitud: "uso de ki mejorado: Cuando usa “Uso de ki” para obtener RD, gana un +1 adicional que se considera de armadura (no equipada). Además, gana una tercera opción para “Uso de ki”; efectúa un ataque que no suma bonos de daño."},
                          {requisitos: '', aptitud: "Percepción sobrenatural: Obtiene +1 en encontrar y abrir cosas. 1xpiso puede rerollear cualquier dado de encontrar o abrir cosas. 1xpiso: 1xronda, si posee “Uso de ki”, puede evadir cualquier efecto o daño; pierde la acción adicional de Uso de ki de su siguiente turno. 1xpiso, si posee “armamento ninja”, sus ataques a distancia son a 6 casillas."},
                          {requisitos: 'Aptitud "Percepción sobrenatural"', aptitud: "Instinto superior: En un piso en el que haya una cantidad variable de tesoros, tira el dado antes de empezar el piso, en lugar de al final. Sin importar el mínimo de acumulación de una cerradura, el ninja siempre puede acumular (con 1 o más). Evadir (de percepción sobrenatural) ya no está limitado a 1xpiso. Por último, el ninja obtiene +1 PE al final de cada piso."} ],
                cdp: [{requisitos: '', aptitud: "Ninja púrpura: *Técnica secreta: 1xturno, usando 1d6 de acción, teletransporta al ninja a cualquier casilla no ocupada del piso y realiza un ataque (con la misma acción) a una criatura adyacente (si lo desea). 1xpiso considera a la teletransportación como si hubiera usado una acción de movimiento, a efectos de activar forma fantasmal."},
                      {requisitos: '', aptitud: "Ninja ocre: 1xturno, usa 1d6 de acción para hacer daño de fuego en una cantidad de casillas consecutivas = igual a nivelx2, a partir de una adyacente; no puede repetirse ninguna casilla. Este daño no se reduce con RD de armadura. Se considera un ataque con arma, por lo que suma daño de arma equipada, pero debe comprar un arma especial (arma especial +1 al daño = 1PP)."}]
            }
          ]
        }
    )
}